/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "../common.h"
#include "../gem.h"
#include "../cpu/arith8.h"
#include "../cpu.h"
#include "../mmu.h"
#include "../gpu.h"
#include "../input.h"

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_INC_B(void);
extern void test_INC_B_overflow(void);
extern void test_INC_B_hc(void);
extern void test_INC_C_overflow(void);
extern void test_DEC_B(void);
extern void test_DEC_B_overflow(void);
extern void test_DEC_B_hc(void);
extern void test_DEC_C_overflow(void);
extern void test_CPL(void);
extern void test_SCF(void);
extern void test_CCF(void);


//=======Test Reset Option=====
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  UnityBegin("test/TestArith8.c");
  RUN_TEST(test_INC_B, 26);
  RUN_TEST(test_INC_B_overflow, 34);
  RUN_TEST(test_INC_B_hc, 43);
  RUN_TEST(test_INC_C_overflow, 52);
  RUN_TEST(test_DEC_B, 63);
  RUN_TEST(test_DEC_B_overflow, 72);
  RUN_TEST(test_DEC_B_hc, 81);
  RUN_TEST(test_DEC_C_overflow, 90);
  RUN_TEST(test_CPL, 101);
  RUN_TEST(test_SCF, 109);
  RUN_TEST(test_CCF, 116);

  return (UnityEnd());
}
